version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/app

  mongodb:
    image: mongo:bionic
    ports:
      - "27017:27017"
    command: mongod --port 27017
